#!/usr/bin/env node
/**
 * Possibly Unused i18n Token Finder
 * Key word: POSSIBLY
 *
 * Looks for i18n tokens that MAY be unused by the code
 * Since some tokens are generated dynamically, the list generated by this script
 * should ALWAYS be verified manually before removing any of the tokens in it
 *
 * Ghostery i18n Tools
 * http://www.ghostery.com/
 *
 * Copyright 2019 Ghostery, Inc. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0
 */

const f = require('./funcs.js');
const empty_string = '';

f.check_node_version_and_quit_if_it_is_too_low();

console.log(process.argv);

const arg = process.argv.length > 1 ? process.argv[2] : empty_string;

switch (arg) {
    case 'init':
        console.log('Doing init stuff');
        break;
    case 'find':
        console.log('Doing find stuff');
        break;
    case 'purge':
        console.log('Doing purge stuff');
        break;
    default:
        console.log('* Instructions *');
}

// f.print_cli_header();
// f.verify_tool_folder_exists_and_make_it_if_it_doesnt();
// f.verify_config_file_exists_and_make_a_default_one_if_it_doesnt();
// // We exit at this point if the config file did not exist
// // Otherwise, we keep going:
// const config = f.load_config_file();
// const tokens = f.load_tokens(config.defaultLocaleTokensFilepath);
// const filepaths = f.load_filepaths(config.locationsToLookForTokens);
// const unusedTokens = f.find_unused_tokens(tokens, filepaths);
// f.save_results(unusedTokens);

